import type { Product } from './types';

export const categories = ["Fruits", "Vegetables", "Bakery"];

export const products: Product[] = [
  {
    id: "prod_001",
    name: "Organic Bananas",
    category: "Fruits",
    price: 1.29,
    imageUrl: "https://placehold.co/600x400.png",
    rating: 4.7,
    reviews: 250,
    description: "A bunch of sweet, organic bananas, rich in potassium.",
    weight: "approx 1 lb",
  },
  {
    id: "prod_002",
    name: "Fresh Strawberries",
    category: "Fruits",
    price: 4.99,
    imageUrl: "https://placehold.co/600x400.png",
    rating: 4.8,
    reviews: 180,
    description: "Juicy and sweet strawberries, perfect for desserts or snacks.",
    weight: "1 lb pack",
  },
  {
    id: "prod_003",
    name: "Hass Avocados",
    category: "Fruits",
    price: 2.50,
    imageUrl: "https://placehold.co/600x400.png",
    rating: 4.9,
    reviews: 420,
    description: "Creamy Hass avocados, ideal for toast, salads, and guacamole.",
    weight: "per avocado",
  },
  {
    id: "prod_004",
    name: "Organic Spinach",
    category: "Vegetables",
    price: 3.49,
    imageUrl: "https://placehold.co/600x400.png",
    rating: 4.6,
    reviews: 150,
    description: "Fresh, pre-washed organic spinach. Great for salads and cooking.",
    weight: "5 oz bag",
  },
  {
    id: "prod_005",
    name: "Cherry Tomatoes",
    category: "Vegetables",
    price: 3.99,
    imageUrl: "https://placehold.co/600x400.png",
    rating: 4.5,
    reviews: 95,
    description: "Sweet and juicy cherry tomatoes on the vine.",
    weight: "1 pint",
  },
  {
    id: "prod_006",
    name: "English Cucumber",
    category: "Vegetables",
    price: 1.79,
    imageUrl: "https://placehold.co/600x400.png",
    rating: 4.7,
    reviews: 110,
    description: "Long, seedless English cucumber with a crisp, refreshing taste.",
    weight: "per cucumber",
  },
  {
    id: "prod_007",
    name: "Sourdough Loaf",
    category: "Bakery",
    price: 6.99,
    imageUrl: "https://placehold.co/600x400.png",
    rating: 4.9,
    reviews: 310,
    description: "Artisan-baked sourdough bread with a chewy crust and soft interior.",
    weight: "1.5 lb loaf",
  },
  {
    id: "prod_008",
    name: "Butter Croissants",
    category: "Bakery",
    price: 5.49,
    imageUrl: "https://placehold.co/600x400.png",
    rating: 4.8,
    reviews: 220,
    description: "Flaky and buttery croissants, freshly baked.",
    weight: "4-pack",
  },
  {
    id: "prod_009",
    name: "Blueberry Muffins",
    category: "Bakery",
    price: 4.99,
    imageUrl: "https://placehold.co/600x400.png",
    rating: 4.7,
    reviews: 175,
    description: "Moist and fluffy muffins packed with juicy blueberries.",
    weight: "4-pack",
  },
];
