
import type { Product } from './types';

export const products: Product[] = [
    {
        id: '1',
        name: 'Авокадо Хасс',
        category: 'Фрукты',
        price: 299.99,
        imageUrl: 'https://placehold.co/600x400.png',
        rating: 4.8,
        reviews: 124,
        description: 'Спелые и кремовые авокадо сорта Хасс, идеально для гуакамоле и тостов. Богат полезными жирами и витаминами.',
        weight: '1 шт',
        weight_category: 'middle',
        min_order_quantity: 1,
        step_quantity: 1,
        nutrition: { calories: 160, protein: 2, fat: 15, carbs: 9 },
        brand: 'Green Giant',
        manufacturer: 'ООО "Фрут-Импорт"',
    },
    {
        id: '2',
        name: 'Молоко "Село Зеленое" 3.2%',
        category: 'Молочные продукты',
        price: 89.50,
        imageUrl: 'https://placehold.co/600x400.png',
        rating: 4.9,
        reviews: 256,
        description: 'Натуральное пастеризованное молоко с жирностью 3.2%. Отлично подходит для каш, кофе и просто как освежающий напиток.',
        weight: '930 мл',
        weight_category: 'middle',
        min_order_quantity: 1,
        step_quantity: 1,
        nutrition: { calories: 60, protein: 3.2, fat: 3.2, carbs: 4.8 },
        brand: 'Село Зеленое',
        manufacturer: 'ОАО "Милком"',
    },
    {
        id: '3',
        name: 'Хлеб "Бородинский"',
        category: 'Выпечка',
        price: 54.00,
        imageUrl: 'https://placehold.co/600x400.png',
        rating: 4.7,
        reviews: 98,
        description: 'Традиционный ржаной хлеб с кориандром. Обладает насыщенным вкусом и ароматом, долго не черствеет.',
        weight: '350 г',
        weight_category: 'light',
        min_order_quantity: 1,
        step_quantity: 1,
        nutrition: { calories: 201, protein: 6.6, fat: 1.3, carbs: 39.8 },
        brand: 'Каравай',
        manufacturer: 'ЗАО "Хлебозавод №5"',
    },
    {
        id: '4',
        name: 'Сыр "Гауда"',
        category: 'Сыры',
        price: 240.00,
        imageUrl: 'https://placehold.co/600x400.png',
        rating: 4.6,
        reviews: 150,
        description: 'Полутвердый сыр с нежным сливочным вкусом. Прекрасно подходит для бутербродов, салатов и сырной тарелки.',
        weight: 'за 100 г',
        weight_category: 'light',
        min_order_quantity: 0.1, // 100g
        step_quantity: 0.1,    // 100g
        nutrition: { calories: 356, protein: 25, fat: 27, carbs: 2 },
        brand: 'President',
        manufacturer: 'Lactalis',
    },
    {
        id: '5',
        name: 'Яйца куриные С0',
        category: 'Яйца',
        price: 110.00,
        imageUrl: 'https://placehold.co/600x400.png',
        rating: 4.9,
        reviews: 312,
        description: 'Отборные куриные яйца высшей категории. Источник белка и незаменимых аминокислот. В упаковке 10 штук.',
        weight: '10 шт',
        weight_category: 'middle',
        min_order_quantity: 1,
        step_quantity: 1,
        nutrition: { calories: 155, protein: 13, fat: 11, carbs: 1.1 },
        brand: 'Волжанин',
        manufacturer: 'ОАО "Птицефабрика Волжанин"',
    },
    {
        id: '6',
        name: 'Картофель молодой',
        category: 'Овощи',
        price: 45.00,
        imageUrl: 'https://placehold.co/600x400.png',
        rating: 4.5,
        reviews: 78,
        description: 'Свежий молодой картофель с тонкой кожицей. Идеально для варки, жарки и запекания.',
        weight: 'за 1 кг',
        weight_category: 'heavy',
        min_order_quantity: 0.5, // 500g
        step_quantity: 0.1,    // 100g
        nutrition: { calories: 77, protein: 2, fat: 0.1, carbs: 17 },
        brand: 'Местные фермеры',
        manufacturer: 'КФХ "Иванов И.И."',
    },
     {
        id: '7',
        name: 'Помидоры Черри',
        category: 'Овощи',
        price: 180.00,
        imageUrl: 'https://placehold.co/600x400.png',
        rating: 4.8,
        reviews: 92,
        description: 'Сладкие и сочные помидоры черри на ветке. Прекрасное дополнение к салатам и закускам.',
        weight: '250 г',
        weight_category: 'light',
        min_order_quantity: 1,
        step_quantity: 1,
        nutrition: { calories: 18, protein: 0.9, fat: 0.2, carbs: 3.9 },
        brand: 'ECO-Culture',
        manufacturer: 'АПХ "ЭКО-культура"',
    },
    {
        id: '8',
        name: 'Бананы',
        category: 'Фрукты',
        price: 85.00,
        imageUrl: 'https://placehold.co/600x400.png',
        rating: 4.7,
        reviews: 189,
        description: 'Спелые бананы из Эквадора. Отличный источник калия и быстрых углеводов для заряда энергией.',
        weight: 'за 1 кг',
        weight_category: 'heavy',
        min_order_quantity: 0.5,
        step_quantity: 0.1,
        nutrition: { calories: 89, protein: 1.1, fat: 0.3, carbs: 23 },
        brand: 'Dole',
        manufacturer: 'Dole Food Company',
    },
];
