import type { Product } from './types';

export const categories = ["Фрукты", "Овощи", "Выпечка", "Молоко, сыр, яйца"];

export const products: Product[] = [
  {
    id: "prod_001",
    name: "Органические бананы",
    category: "Фрукты",
    price: 120, 
    imageUrl: "https://placehold.co/600x400.png",
    rating: 4.7,
    reviews: 250,
    description: "Сладкие органические бананы, богатые калием. Выращены на лучших плантациях без использования химических удобрений, что гарантирует их натуральный вкус и пользу для здоровья.",
    weight: "около 450 г",
    weight_category: 'middle',
    min_order_quantity: 0.5,
    step_quantity: 0.5,
    nutrition: { calories: 89, protein: 1.1, fat: 0.3, carbs: 22.8 },
    brand: "ЭкоФрукт",
    manufacturer: "ООО 'Солнечные плантации'",
  },
  {
    id: "prod_002",
    name: "Свежая клубника",
    category: "Фрукты",
    price: 500,
    imageUrl: "https://placehold.co/600x400.png",
    rating: 4.8,
    reviews: 180,
    description: "Сочная и сладкая клубника, идеально подходит для десертов и закусок. Наша клубника собирается вручную на пике спелости, чтобы вы могли насладиться ее неповторимым ароматом.",
    weight: "упаковка 450 г",
    weight_category: 'none',
    min_order_quantity: 1,
    step_quantity: 1,
    nutrition: { calories: 32, protein: 0.7, fat: 0.3, carbs: 7.7 },
    brand: "Ягодная долина",
    manufacturer: "КФХ 'Красная ягода'",
  },
  {
    id: "prod_003",
    name: "Авокадо Хасс",
    category: "Фрукты",
    price: 350,
    imageUrl: "https://placehold.co/600x400.png",
    rating: 4.9,
    reviews: 420,
    description: "Сливочные авокадо Хасс, идеально подходят для тостов, салатов и гуакамоле. Отличаются нежной текстурой и насыщенным вкусом.",
    weight: "за шт.",
    weight_category: 'none',
    min_order_quantity: 1,
    step_quantity: 1,
    nutrition: { calories: 160, protein: 2, fat: 15, carbs: 9 },
    brand: "Авокадо Мир",
    manufacturer: "Импорт-Экзотик",
  },
  {
    id: "prod_004",
    name: "Органический шпинат",
    category: "Овощи",
    price: 300,
    imageUrl: "https://placehold.co/600x400.png",
    rating: 4.6,
    reviews: 150,
    description: "Свежий, предварительно вымытый органический шпинат. Отлично подходит для салатов и приготовления пищи. Богат витаминами и минералами.",
    weight: "пакет 140 г",
    weight_category: 'light',
    min_order_quantity: 0.1,
    step_quantity: 0.1,
    nutrition: { calories: 23, protein: 2.9, fat: 0.4, carbs: 3.6 },
    brand: "Зеленая грядка",
    manufacturer: "ООО 'Органик-Фудс'",
  },
  {
    id: "prod_005",
    name: "Помидоры черри",
    category: "Овощи",
    price: 400,
    imageUrl: "https://placehold.co/600x400.png",
    rating: 4.5,
    reviews: 95,
    description: "Сладкие и сочные помидоры черри на ветке. Идеальны для перекусов и добавления в салаты.",
    weight: "1 пинта",
    weight_category: 'middle',
    min_order_quantity: 0.5,
    step_quantity: 0.5,
    nutrition: { calories: 18, protein: 0.9, fat: 0.2, carbs: 3.9 },
    brand: "Сочные томаты",
    manufacturer: "Агрокомплекс 'Солнечный'",
  },
  {
    id: "prod_006",
    name: "Английский огурец",
    category: "Овощи",
    price: 200,
    imageUrl: "https://placehold.co/600x400.png",
    rating: 4.7,
    reviews: 110,
    description: "Длинный английский огурец без косточек с хрустящим, освежающим вкусом. Прекрасно подходит для свежих салатов и сэндвичей.",
    weight: "за огурец",
    weight_category: 'none',
    min_order_quantity: 1,
    step_quantity: 1,
    nutrition: { calories: 15, protein: 0.7, fat: 0.1, carbs: 3.6 },
    brand: "Свежесть",
    manufacturer: "Тепличный комбинат 'Зеленый мир'",
  },
  {
    id: "prod_007",
    name: "Буханка на закваске",
    category: "Выпечка",
    price: 700,
    imageUrl: "https://placehold.co/600x400.png",
    rating: 4.9,
    reviews: 310,
    description: "Ремесленный хлеб на закваске с жевательной корочкой и мягкой внутренней частью. Выпекается по традиционным рецептам.",
    weight: "буханка 680 г",
    weight_category: 'none',
    min_order_quantity: 1,
    step_quantity: 1,
    nutrition: { calories: 265, protein: 9, fat: 3.2, carbs: 49 },
    brand: "Пекарня №1",
    manufacturer: "ИП Хлебников",
  },
  {
    id: "prod_008",
    name: "Сливочные круассаны",
    category: "Выпечка",
    price: 550,
    imageUrl: "https://placehold.co/600x400.png",
    rating: 4.8,
    reviews: 220,
    description: "Свежеиспеченные слоеные и маслянистые круассаны. Идеальное начало дня с чашечкой кофе.",
    weight: "упаковка 4 шт.",
    weight_category: 'none',
    min_order_quantity: 1,
    step_quantity: 1,
    nutrition: { calories: 406, protein: 8, fat: 21, carbs: 46 },
    brand: "Французская булочка",
    manufacturer: "Кондитерская 'Бонжур'",
  },
  {
    id: "prod_009",
    name: "Черничные маффины",
    category: "Выпечка",
    price: 500,
    imageUrl: "https://placehold.co/600x400.png",
    rating: 4.7,
    reviews: 175,
    description: "Влажные и пышные кексы с сочной черникой. Отличный выбор для десерта или перекуса.",
    weight: "упаковка 4 шт.",
    weight_category: 'none',
    min_order_quantity: 1,
    step_quantity: 1,
    nutrition: { calories: 370, protein: 4.5, fat: 18, carbs: 48 },
    brand: "Сладкоежка",
    manufacturer: "ООО 'Маффин Хаус'",
  },
  {
    id: "prod_010",
    name: "Сыр Сулугуни",
    category: "Молоко, сыр, яйца",
    price: 800,
    imageUrl: "https://placehold.co/600x400.png",
    rating: 4.9,
    reviews: 98,
    description: "Традиционный грузинский сыр с нежным, солоноватым вкусом. Идеален для хачапури и салатов.",
    weight: "за кг",
    weight_category: 'light',
    min_order_quantity: 0.2,
    step_quantity: 0.1,
    nutrition: { calories: 290, protein: 22, fat: 22, carbs: 0 },
    brand: "Кавказские сыры",
    manufacturer: "Сыроварня 'Горы'",
  },
  {
    id: "prod_011",
    name: "Яйцо домашнее",
    category: "Молоко, сыр, яйца",
    price: 250,
    imageUrl: "https://placehold.co/600x400.png",
    rating: 5.0,
    reviews: 150,
    description: "Свежие домашние яйца от кур свободного выгула. Яркий желток и натуральный вкус.",
    weight: "10 шт",
    weight_category: 'none',
    min_order_quantity: 1,
    step_quantity: 1,
    nutrition: { calories: 155, protein: 13, fat: 11, carbs: 1.1 },
    brand: "Фермерское подворье",
    manufacturer: "ЛПХ Сидоренко",
  },
  {
    id: "prod_012",
    name: "Тыква",
    category: "Овощи",
    price: 150,
    imageUrl: "https://placehold.co/600x400.png",
    rating: 4.6,
    reviews: 45,
    description: "Сладкая и ароматная тыква, отлично подходит для супов, запекания и десертов.",
    weight: "за кг",
    weight_category: 'middle',
    min_order_quantity: 0.5,
    step_quantity: 0.5,
    nutrition: { calories: 26, protein: 1, fat: 0.1, carbs: 7 },
    brand: "Дары осени",
    manufacturer: "Агрофирма 'Золотая бахча'",
  },
  {
    id: "prod_013",
    name: "Арбуз",
    category: "Фрукты",
    price: 80,
    imageUrl: "https://placehold.co/600x400.png",
    rating: 4.8,
    reviews: 123,
    description: "Сочный и сладкий астраханский арбуз. Лучшее летнее лакомство для всей семьи.",
    weight: "за кг",
    weight_category: 'heavy',
    min_order_quantity: 2,
    step_quantity: 1,
    nutrition: { calories: 30, protein: 0.6, fat: 0.2, carbs: 8 },
    brand: "Дары Кубани",
    manufacturer: "КФХ 'Арбузный рай'",
  },
];
